//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.02 at 07:04:45 PM IST 
//

package org.xwiki.android.resources;

import java.util.Calendar;
import java.util.Collection;

/*
 import javax.xml.bind.annotation.XmlAccessType;
 import javax.xml.bind.annotation.XmlAccessorType;
 import javax.xml.bind.annotation.XmlElement;
 import javax.xml.bind.annotation.XmlRootElement;
 import javax.xml.bind.annotation.XmlSchemaType;
 import javax.xml.bind.annotation.XmlType;
 import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
 */

/**
 * <p>
 * Java class for Comment complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Comment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xwiki.org}LinkCollection">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="highlight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="replyTo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
/*
 * //@XmlAccessorType(XmlAccessType.FIELD) //@XmlType(name = "Comment", propOrder = { "id", "pageId", "author", "date",
 * "highlight", "text", "replyTo" }) //@XmlRootElement(name = "comment")
 */
public class Comment extends LinkCollection
{

    public int id;

    // @XmlElement(required = true)
    public String pageId;

    // @XmlElement(required = true)
    public String author;

    // @XmlElement(required = true, type = String.class)
    // @XmlJavaTypeAdapter(Adapter1 .class)
    // @XmlSchemaType(name = "dateTime")
    public Calendar date;

    // @XmlElement(required = true)
    public String highlight;

    // @XmlElement(required = true)
    public String text;

    // @XmlElement(required = true, type = Integer.class, nillable = true)
    public Integer replyTo;

    /**
     * Gets the value of the id property.
     */
    public int getId()
    {
        return id;
    }

    /**
     * Sets the value of the id property.
     */
    public void setId(int value)
    {
        this.id = value;
    }

    /**
     * Gets the value of the pageId property.
     * 
     * @return possible object is {@link String }
     */
    public String getPageId()
    {
        return pageId;
    }

    /**
     * Sets the value of the pageId property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPageId(String value)
    {
        this.pageId = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return possible object is {@link String }
     */
    public String getAuthor()
    {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setAuthor(String value)
    {
        this.author = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return possible object is {@link String }
     */
    public Calendar getDate()
    {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDate(Calendar value)
    {
        this.date = value;
    }

    /**
     * Gets the value of the highlight property.
     * 
     * @return possible object is {@link String }
     */
    public String getHighlight()
    {
        return highlight;
    }

    /**
     * Sets the value of the highlight property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setHighlight(String value)
    {
        this.highlight = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return possible object is {@link String }
     */
    public String getText()
    {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setText(String value)
    {
        this.text = value;
    }

    /**
     * Gets the value of the replyTo property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getReplyTo()
    {
        return replyTo;
    }

    /**
     * Sets the value of the replyTo property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setReplyTo(Integer value)
    {
        this.replyTo = value;
    }

    public Comment withId(int value)
    {
        setId(value);
        return this;
    }

    public Comment withPageId(String value)
    {
        setPageId(value);
        return this;
    }

    public Comment withAuthor(String value)
    {
        setAuthor(value);
        return this;
    }

    public Comment withDate(Calendar value)
    {
        setDate(value);
        return this;
    }

    public Comment withHighlight(String value)
    {
        setHighlight(value);
        return this;
    }

    public Comment withText(String value)
    {
        setText(value);
        return this;
    }

    public Comment withReplyTo(Integer value)
    {
        setReplyTo(value);
        return this;
    }

    @Override
    public Comment withLinks(Link... values)
    {
        if (values != null) {
            for (Link value : values) {
                getLinks().add(value);
            }
        }
        return this;
    }

    @Override
    public Comment withLinks(Collection<Link> values)
    {
        if (values != null) {
            getLinks().addAll(values);
        }
        return this;
    }

}
