//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.02 at 07:04:45 PM IST 
//

package org.xwiki.android.resources;

import java.util.GregorianCalendar;

import java.util.Collection;

/*
 import javax.xml.bind.annotation.XmlAccessType;
 import javax.xml.bind.annotation.XmlAccessorType;
 import javax.xml.bind.annotation.XmlElement;
 import javax.xml.bind.annotation.XmlRootElement;
 import javax.xml.bind.annotation.XmlSchemaType;
 import javax.xml.bind.annotation.XmlType;
 import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
 */

/**
 * <p>
 * Java class for Page complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Page">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xwiki.org}PageSummary">
 *       &lt;sequence>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="majorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="minorVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="created" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="creator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modified" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="modifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
/*
 * //@XmlAccessorType(XmlAccessType.FIELD) //@XmlType(name = "Page", propOrder = { "language", "version",
 * "majorVersion", "minorVersion", "created", "creator", "modified", "modifier", "content" }) //@XmlRootElement(name =
 * "page")
 */
public class Page extends PageSummary
{

    // @XmlElement(required = true)
    public String language;

    // @XmlElement(required = true)
    public String version;

    public int majorVersion;

    public int minorVersion;

    // @XmlElement(required = true, type = String.class)
    // @XmlJavaTypeAdapter(Adapter1 .class)
    // @XmlSchemaType(name = "dateTime")
    public GregorianCalendar created1;

    // @XmlElement(required = true)
    public String creator;

    // @XmlElement(required = true, type = String.class)
    // @XmlJavaTypeAdapter(Adapter1 .class)
    // @XmlSchemaType(name = "dateTime")
    public GregorianCalendar modified1;

    // @XmlElement(required = true)
    public String modifier;

    // @XmlElement(required = true)
    public String content;

    /**
     * Gets the value of the language property.
     * 
     * @return possible object is {@link String }
     */
    public String getLanguage()
    {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setLanguage(String value)
    {
        this.language = value;
        
    }

    /**
     * Gets the value of the version property.
     * 
     * @return possible object is {@link String }
     */
    public String getVersion()
    {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setVersion(String value)
    {
        this.version = value;
    }

    /**
     * Gets the value of the majorVersion property.
     */
    public int getMajorVersion()
    {
        return majorVersion;
    }

    /**
     * Sets the value of the majorVersion property.
     */
    public void setMajorVersion(int value)
    {
        this.majorVersion = value;
    }

    /**
     * Gets the value of the minorVersion property.
     */
    public int getMinorVersion()
    {
        return minorVersion;
    }

    /**
     * Sets the value of the minorVersion property.
     */
    public void setMinorVersion(int value)
    {
        this.minorVersion = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return possible object is {@link String }
     */
    public GregorianCalendar getCreated()
    {
        return created1;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setCreated(GregorianCalendar value)
    {
        this.created1 = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return possible object is {@link String }
     */
    public String getCreator()
    {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setCreator(String value)
    {
        this.creator = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     * @return possible object is {@link String }
     */
    public GregorianCalendar getModified()
    {
        return modified1;
    }

    /**
     * Sets the value of the modified property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setModified(GregorianCalendar value)
    {
        this.modified1 = value;
    }

    /**
     * Gets the value of the modifier property.
     * 
     * @return possible object is {@link String }
     */
    public String getModifier()
    {
        return modifier;
    }

    /**
     * Sets the value of the modifier property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setModifier(String value)
    {
        this.modifier = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return possible object is {@link String }
     */
    public String getContent()
    {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setContent(String value)
    {
        this.content = value;
    }

    public Page withLanguage(String value)
    {
        setLanguage(value);
        return this;
    }

    public Page withVersion(String value)
    {
        setVersion(value);
        return this;
    }

    public Page withMajorVersion(int value)
    {
        setMajorVersion(value);
        return this;
    }

    public Page withMinorVersion(int value)
    {
        setMinorVersion(value);
        return this;
    }

    public Page withCreated(GregorianCalendar value)
    {
        setCreated(value);
        return this;
    }

    public Page withCreator(String value)
    {
        setCreator(value);
        return this;
    }

    public Page withModified(GregorianCalendar value)
    {
        setModified(value);
        return this;
    }

    public Page withModifier(String value)
    {
        setModifier(value);
        return this;
    }

    public Page withContent(String value)
    {
        setContent(value);
        return this;
    }

    @Override
    public Page withId(String value)
    {
        setId(value);
        return this;
    }

    @Override
    public Page withFullName(String value)
    {
        setFullName(value);
        return this;
    }

    @Override
    public Page withWiki(String value)
    {
        setWiki(value);
        return this;
    }

    @Override
    public Page withSpace(String value)
    {
        setSpace(value);
        return this;
    }

    @Override
    public Page withName(String value)
    {
        setName(value);
        return this;
    }

    @Override
    public Page withTitle(String value)
    {
        setTitle(value);
        return this;
    }

    @Override
    public Page withParent(String value)
    {
        setParent(value);
        return this;
    }

    @Override
    public Page withParentId(String value)
    {
        setParentId(value);
        return this;
    }

    @Override
    public Page withXwikiRelativeUrl(String value)
    {
        setXwikiRelativeUrl(value);
        return this;
    }

    @Override
    public Page withXwikiAbsoluteUrl(String value)
    {
        setXwikiAbsoluteUrl(value);
        return this;
    }

    @Override
    public Page withTranslations(Translations value)
    {
        setTranslations(value);
        return this;
    }

    @Override
    public Page withSyntax(String value)
    {
        setSyntax(value);
        return this;
    }

    @Override
    public Page withLinks(Link... values)
    {
        if (values != null) {
            for (Link value : values) {
                getLinks().add(value);
            }
        }
        return this;
    }

    @Override
    public Page withLinks(Collection<Link> values)
    {
        if (values != null) {
            getLinks().addAll(values);
        }
        return this;
    }

}
