//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.02 at 07:04:45 PM IST 
//

package org.xwiki.android.resources;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/*
 import javax.xml.bind.annotation.XmlAccessType;
 import javax.xml.bind.annotation.XmlAccessorType;
 import javax.xml.bind.annotation.XmlElement;
 import javax.xml.bind.annotation.XmlRootElement;
 import javax.xml.bind.annotation.XmlType;
 */

/**
 * <p>
 * Java class for Syntaxes complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Syntaxes">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xwiki.org}LinkCollection">
 *       &lt;sequence>
 *         &lt;element name="syntax" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
/*
 * //@XmlAccessorType(XmlAccessType.FIELD) //@XmlType(name = "Syntaxes", propOrder = { "syntaxes" })
 * //@XmlRootElement(name = "syntaxes")
 */
public class Syntaxes extends LinkCollection
{

    // @XmlElement(name = "syntax")
    public List<String> syntaxes;

    /**
     * Gets the value of the syntaxes property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the syntaxes property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSyntaxes().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     */
    public List<String> getSyntaxes()
    {
        if (syntaxes == null) {
            syntaxes = new ArrayList<String>();
        }
        return this.syntaxes;
    }

    public Syntaxes withSyntaxes(String... values)
    {
        if (values != null) {
            for (String value : values) {
                getSyntaxes().add(value);
            }
        }
        return this;
    }

    public Syntaxes withSyntaxes(Collection<String> values)
    {
        if (values != null) {
            getSyntaxes().addAll(values);
        }
        return this;
    }

    @Override
    public Syntaxes withLinks(Link... values)
    {
        if (values != null) {
            for (Link value : values) {
                getLinks().add(value);
            }
        }
        return this;
    }

    @Override
    public Syntaxes withLinks(Collection<Link> values)
    {
        if (values != null) {
            getLinks().addAll(values);
        }
        return this;
    }

}
