//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.02 at 07:04:45 PM IST 
//

package org.xwiki.android.resources;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Namespace;
import org.simpleframework.xml.Root;

/*
 import javax.xml.bind.annotation.XmlAccessType;
 import javax.xml.bind.annotation.XmlAccessorType;
 import javax.xml.bind.annotation.XmlElement;
 import javax.xml.bind.annotation.XmlRootElement;
 import javax.xml.bind.annotation.XmlType;
 */

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xwiki.org}LinkCollection">
 *       &lt;sequence>
 *         &lt;element name="historySummary" type="{http://www.xwiki.org}HistorySummary" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
/*
 * //@XmlAccessorType(XmlAccessType.FIELD) //@XmlType(name = "", propOrder = { "historySummaries" })
 * //@XmlRootElement(name = "history")
 */
@Root
@Namespace(reference="http://www.xwiki.org")
public class History //extends LinkCollection
{

    // @XmlElement(name = "historySummary")
    @ElementList(name = "historySummary", inline=true)
    public List<HistorySummary> historySummaries;

    /**
     * Gets the value of the historySummaries property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the historySummaries property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getHistorySummaries().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link HistorySummary }
     */
    public List<HistorySummary> getHistorySummaries()
    {
        if (historySummaries == null) {
            historySummaries = new ArrayList<HistorySummary>();
        }
        return this.historySummaries;
    }

    public History withHistorySummaries(HistorySummary... values)
    {
        if (values != null) {
            for (HistorySummary value : values) {
                getHistorySummaries().add(value);
            }
        }
        return this;
    }

    public History withHistorySummaries(Collection<HistorySummary> values)
    {
        if (values != null) {
            getHistorySummaries().addAll(values);
        }
        return this;
    }

    /*
    @Override
    public History withLinks(Link... values)
    {
        if (values != null) {
            for (Link value : values) {
                getLinks().add(value);
            }
        }
        return this;
    }

    @Override
    public History withLinks(Collection<Link> values)
    {
        if (values != null) {
            getLinks().addAll(values);
        }
        return this;
    }
    */
}
