//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.02 at 07:04:45 PM IST 
//

package org.xwiki.android.resources;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

/*
 import javax.xml.bind.annotation.XmlAccessType;
 import javax.xml.bind.annotation.XmlAccessorType;
 import javax.xml.bind.annotation.XmlAttribute;
 import javax.xml.bind.annotation.XmlType;
 */

/**
 * <p>
 * Java class for Link complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Link">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hrefLang" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
/*
 * //@XmlAccessorType(XmlAccessType.FIELD) //@XmlType(name = "Link")
 */
@Root
public class Link
{

    // @XmlAttribute
    @Attribute(required=false)
    public String href;

    // @XmlAttribute
    @Attribute(required=false)
    public String rel;

    // @XmlAttribute
    @Attribute(required=false)
    public String type;

    // @XmlAttribute
    @Attribute(required=false)
    public String hrefLang;

    /**
     * Gets the value of the href property.
     * 
     * @return possible object is {@link String }
     */
    public String getHref()
    {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setHref(String value)
    {
        this.href = value;
    }

    /**
     * Gets the value of the rel property.
     * 
     * @return possible object is {@link String }
     */
    public String getRel()
    {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRel(String value)
    {
        this.rel = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     */
    public String getType()
    {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setType(String value)
    {
        this.type = value;
    }

    /**
     * Gets the value of the hrefLang property.
     * 
     * @return possible object is {@link String }
     */
    public String getHrefLang()
    {
        return hrefLang;
    }

    /**
     * Sets the value of the hrefLang property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setHrefLang(String value)
    {
        this.hrefLang = value;
    }

    public Link withHref(String value)
    {
        setHref(value);
        return this;
    }

    public Link withRel(String value)
    {
        setRel(value);
        return this;
    }

    public Link withType(String value)
    {
        setType(value);
        return this;
    }

    public Link withHrefLang(String value)
    {
        setHrefLang(value);
        return this;
    }

}
