//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.02 at 07:04:45 PM IST 
//

package org.xwiki.android.resources;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Root;

/*
 import javax.xml.bind.annotation.XmlAccessType;
 import javax.xml.bind.annotation.XmlAccessorType;
 import javax.xml.bind.annotation.XmlElement;
 import javax.xml.bind.annotation.XmlSeeAlso;
 import javax.xml.bind.annotation.XmlType;
 */

/**
 * <p>
 * Java class for LinkCollection complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinkCollection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="link" type="{http://www.xwiki.org}Link" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
/*
 * @XmlAccessorType(XmlAccessType.FIELD)
 * @XmlType(name = "LinkCollection", propOrder = { "links" })
 * @XmlSeeAlso({ Attribute.class, HistorySummary.class, Translation.class, Comments.class, Syntaxes.class,
 * Comment.class, Translations.class, SearchResults.class, History.class, Properties.class, Attachment.class,
 * Property.class, Class.class, Pages.class, Spaces.class, Tags.class, Classes.class, Objects.class, Wiki.class,
 * Attachments.class, PageSummary.class, SearchResult.class, Space.class, ObjectSummary.class, Xwiki.class, Tag.class,
 * Wikis.class })
 */
@Element
public class LinkCollection
{

    // @XmlElement(name = "link")
    @ElementList(name = "link",inline=true, required=false)
    public List<Link> links;
 
    /**
     * Gets the value of the links property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the links property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getLinks().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Link }
     */
    public List<Link> getLinks()
    {
        if (links == null) {
            links = new ArrayList<Link>();
        }
        return this.links;
    }

    public LinkCollection withLinks(Link... values)
    {
        if (values != null) {
            for (Link value : values) {
                getLinks().add(value);
            }
        }
        return this;
    }

    public LinkCollection withLinks(Collection<Link> values)
    {
        if (values != null) {
            getLinks().addAll(values);
        }
        return this;
    }

}
