//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.02 at 07:04:45 PM IST 
//

package org.xwiki.android.resources;

import java.util.Collection;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Namespace;
import org.simpleframework.xml.Root;

/*
 import javax.xml.bind.annotation.XmlAccessType;
 import javax.xml.bind.annotation.XmlAccessorType;
 import javax.xml.bind.annotation.XmlElement;
 import javax.xml.bind.annotation.XmlSeeAlso;
 import javax.xml.bind.annotation.XmlType;
 */

/**
 * <p>
 * Java class for ObjectSummary complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectSummary">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xwiki.org}LinkCollection">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wiki" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="space" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="headline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
/*
 * //@XmlAccessorType(XmlAccessType.FIELD) //@XmlType(name = "ObjectSummary", propOrder = { "id", "guid", "pageId",
 * "wiki", "space", "pageName", "className", "number", "headline" }) //@XmlSeeAlso({ Object.class })
 */
@Root
@Namespace(reference="http://www.xwiki.org")
public class ObjectSummary extends LinkCollection
{

    // @XmlElement(required = true)
    @Element(required = false)
    public String id;

    // @XmlElement(required = true)
    @Element(required = false)
    public String guid;

    // @XmlElement(required = true)
    @Element(required = false)
    public String pageId;

    // @XmlElement(required = true)
    @Element(required = false)
    public String wiki;

    // @XmlElement(required = true)
    @Element(required = false)
    public String space;

    // @XmlElement(required = true)
    @Element(required = false)
    public String pageName;

    // @XmlElement(required = true)
    @Element(required = false)
    public String className;

    @Element(required = false)
    public int number;

    // @XmlElement(required = true)
    @Element(required = false)
    public String headline;

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     */
    public String getId()
    {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setId(String value)
    {
        this.id = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return possible object is {@link String }
     */
    public String getGuid()
    {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setGuid(String value)
    {
        this.guid = value;
    }

    /**
     * Gets the value of the pageId property.
     * 
     * @return possible object is {@link String }
     */
    public String getPageId()
    {
        return pageId;
    }

    /**
     * Sets the value of the pageId property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPageId(String value)
    {
        this.pageId = value;
    }

    /**
     * Gets the value of the wiki property.
     * 
     * @return possible object is {@link String }
     */
    public String getWiki()
    {
        return wiki;
    }

    /**
     * Sets the value of the wiki property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setWiki(String value)
    {
        this.wiki = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return possible object is {@link String }
     */
    public String getSpace()
    {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setSpace(String value)
    {
        this.space = value;
    }

    /**
     * Gets the value of the pageName property.
     * 
     * @return possible object is {@link String }
     */
    public String getPageName()
    {
        return pageName;
    }

    /**
     * Sets the value of the pageName property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPageName(String value)
    {
        this.pageName = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return possible object is {@link String }
     */
    public String getClassName()
    {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setClassName(String value)
    {
        this.className = value;
    }

    /**
     * Gets the value of the number property.
     */
    public int getNumber()
    {
        return number;
    }

    /**
     * Sets the value of the number property.
     */
    public void setNumber(int value)
    {
        this.number = value;
    }

    /**
     * Gets the value of the headline property.
     * 
     * @return possible object is {@link String }
     */
    public String getHeadline()
    {
        return headline;
    }

    /**
     * Sets the value of the headline property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setHeadline(String value)
    {
        this.headline = value;
    }

    public ObjectSummary withId(String value)
    {
        setId(value);
        return this;
    }

    public ObjectSummary withGuid(String value)
    {
        setGuid(value);
        return this;
    }

    public ObjectSummary withPageId(String value)
    {
        setPageId(value);
        return this;
    }

    public ObjectSummary withWiki(String value)
    {
        setWiki(value);
        return this;
    }

    public ObjectSummary withSpace(String value)
    {
        setSpace(value);
        return this;
    }

    public ObjectSummary withPageName(String value)
    {
        setPageName(value);
        return this;
    }

    public ObjectSummary withClassName(String value)
    {
        setClassName(value);
        return this;
    }

    public ObjectSummary withNumber(int value)
    {
        setNumber(value);
        return this;
    }

    public ObjectSummary withHeadline(String value)
    {
        setHeadline(value);
        return this;
    }

    @Override
    public ObjectSummary withLinks(Link... values)
    {
        if (values != null) {
            for (Link value : values) {
                getLinks().add(value);
            }
        }
        return this;
    }

    @Override
    public ObjectSummary withLinks(Collection<Link> values)
    {
        if (values != null) {
            getLinks().addAll(values);
        }
        return this;
    }

}
