//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.02 at 07:04:45 PM IST 
//

package org.xwiki.android.resources;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Namespace;
import org.simpleframework.xml.Root;

/*
 import javax.xml.bind.annotation.XmlAccessType;
 import javax.xml.bind.annotation.XmlAccessorType;
 import javax.xml.bind.annotation.XmlAttribute;
 import javax.xml.bind.annotation.XmlElement;
 import javax.xml.bind.annotation.XmlRootElement;
 import javax.xml.bind.annotation.XmlType;
 */

/**
 * <p>
 * Java class for Translations complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Translations">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xwiki.org}LinkCollection">
 *       &lt;sequence>
 *         &lt;element name="translation" type="{http://www.xwiki.org}Translation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
/*
 * //@XmlAccessorType(XmlAccessType.FIELD) //@XmlType(name = "Translations", propOrder = { "translations" })
 * //@XmlRootElement(name = "translations")
 */
@Root
@Namespace(reference="http://www.xwiki.org")
public class Translations //extends LinkCollection
{

    // @XmlElement(name = "translation")
    @ElementList(name = "translation", inline=true, required= false)
    public List<Translation> translations;

    // @XmlAttribute(name = "default")
    @Attribute(required = false)
    public String _default;

    /**
     * Gets the value of the translations property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the translations property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTranslations().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Translation }
     */
    public List<Translation> getTranslations()
    {
        if (translations == null) {
            translations = new ArrayList<Translation>();
        }
        return this.translations;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return possible object is {@link String }
     */
    public String getDefault()
    {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDefault(String value)
    {
        this._default = value;
    }

    public Translations withTranslations(Translation... values)
    {
        if (values != null) {
            for (Translation value : values) {
                getTranslations().add(value);
            }
        }
        return this;
    }

    public Translations withTranslations(Collection<Translation> values)
    {
        if (values != null) {
            getTranslations().addAll(values);
        }
        return this;
    }

    public Translations withDefault(String value)
    {
        setDefault(value);
        return this;
    }

    /*
    @Override
    public Translations withLinks(Link... values)
    {
        if (values != null) {
            for (Link value : values) {
                getLinks().add(value);
            }
        }
        return this;
    }

    @Override
    public Translations withLinks(Collection<Link> values)
    {
        if (values != null) {
            getLinks().addAll(values);
        }
        return this;
    }
    */
}
